=== mithradharmarajvelu-art/app/student.dtd
<!ELEMENT student (rollno, name, department, year)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== mithradharmarajvelu-art/app/student_formatted.xml
<<<<<<< HEAD
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <rollno>101</rollno>
    <name>Mithra</name>
    <department>CSE</department>
    <year>Final Year</year>
</student>
=======
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <rollno>101</rollno>
    <name>Mithra</name>
    <department>CSE</department>
    <year>Final Year</year>
</student>
>>>>>>> 51a9ef2dde3be4af1c912d17ecbe5da1cd355793
